version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:
